data:
  url: "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
  raw_dir: "./data/raw"
  processed_dir: "./data/processed"
  test_size: 0.2
  val_size: 0.2
  random_state: 42
  
  n_batches: 5                    # На скільки частин ділимо тренувальні дані
  batch_names_select: ["0", "1", "2", "3", "4"]  # Які саме частини беремо для поточного експерименту

training:
  batch_size: 64
  lr: 0.001
  num_epochs: 10
  device: "cpu"

model:
  n_classes: 10
  save_path: "artifacts/best_model_lab2.pth"